; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-zero]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
	NeoPixelBus	
	robtillaart/PCF8575@^0.1.10
  AsyncTCP
  ESP32_NOW
  ; MQTT
  ArduinoJson
  ; ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
  ; me-no-dev/ESP Async WebServer @ ^1.2.3

board_build.filesystem = littlefs
board_build.f_flash = 40000000L
board_build.flash_mode = dio
monitor_speed = 460800
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
 